name: Deploy Application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release-chart:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"


  BuildandRun:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: "latest"
        id: install

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.14.2'

      - name: Add Helm repository
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update

      - name: Deploy Prometheus
        run: helm install prometheus prometheus-community/kube-prometheus-stack
      
      - name: Deploy Helm Chart
        run: |
          helm repo add todo-app https://merdang.github.io/todo-app
          helm repo update
          helm install todo-app todo-app/todo-app

