name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 1.29
        id: install

      - name: Install KinD
        run: |
          [ $(uname -m) = x86_64 ] && curl -Lo kind https://kind.sigs.k8s.io/dl/v0.11.1/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind
          kind version

      - name: Create KinD cluster
        run: kind create cluster

  deploy-prometheus: # needed for charts deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: 'v3.14.2'

      - name: Add Helm repository
        run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

      - name: Deploy PostgreSQL
        run: helm install prometheus prometheus-community/kube-prometheus-stack
  
  deploy-helm-chart:
    runs-on: ubuntu-latest
    needs: deploy-prometheus
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy Helm Chart
        run: |
          helm install todo-app ./charts/todo-app